In [1]:
# Import the functions from /tools
import math
import os

# You need to choose one of the api's or hf's "request_llm" function here. 
# from tools.hf_open_source_llm_request import request_llm
# from tools.api_request import request_gpt as request_llm
from tools.api_request import request_gemini as request_llm 

from tools.db_detail import db_getdesc
from tools.db_detail import db_getnames
from tools.sql_execute import sqlite_execute as execute
from tqdm import tqdm
import json
import argparse

def sql_evoke(query,db_name):
    result, execution_time ,executable = execute("datasets/cosql_dataset/database/"+db_name+"/"+db_name+".sqlite",query)
    return result 

def get_example(db_name):
    sql_query = "SELECT name FROM sqlite_master WHERE type='table';"
    result = sql_evoke(sql_query,db_name)
    column_example=""
    for table_name in result:
        column_example = column_example + table_name[0] + ":\n"
        sql_get_eg = "SELECT * FROM "+ table_name[0] +" LIMIT 3;"
        table_eg = sql_evoke(sql_get_eg,db_name)
        for table_data in table_eg:
            column_example = column_example + '('
            for column_data in table_data: 
                column_example = column_example + str(column_data) +','
            column_example = column_example[:-1] + ')\n'
    return column_example

# print(db_getdesc("car_1"),get_example("car_1"))

In [2]:
from agents.rewriter import Rewriter
from agents.selector import Selector
from agents.detector import Detector
from agents.decomposer import Decomposer
from agents.refiner import Refiner

# creat and name the agents
rewriter = Rewriter("Rewriter")
selector = Selector("Selector")
detector = Detector("Detector")
decomposer = Decomposer("Decomposer")
refiner = Refiner("Refiner")

# input_data = "hey!"
# output_rewriter = rewriter.process_input(input_data)
# output_selector = selector.process_input(input_data)
# output_detector = detector.process_input(input_data)
# output_decomposer = decomposer.process_input(input_data)
# output_refiner = refiner.process_input(input_data)

In [ ]:
def process_json_part(data, output_file):
    for index1,item in enumerate(tqdm(data)):
        retries = 0
        while retries < 2:
            try:
                # Initialnize messages
                print("Turn "+str(index1)+" ==================================================================")
                db_name = item['db_name']
                previous_QA = ""
                
                
                for index, turn in enumerate(item['turns']):
                    
                    if turn['isuser']:
                        final_output = ""
                        output_rewriter = ""
                        output_selector = ""
                        output_detector = ""
                        output_decomposer = ""
                        output_refiner = ""
                        final_output = ""
                        sql_output = ""
                        user_question = turn['text']
                        question_type = turn['type']
        
                        print("previous_QA " + ":" + previous_QA)
                        print("question " + str(index//2) + ":\033[93m " + user_question + "\033[0m")
                        
                        if index+1<len(item['turns']):
        
                            # print("________Question rewriter________")
                            # input_data = {
                            #     "db_desc": db_getnames(db_name),
                            #     "evidence": "",
                            #     "question": user_question,
                            #     "previous_QA": previous_QA
                            # }
                            
                            # output_rewriter = rewriter.process_input(input_data)
                            
                            # if output_rewriter["improper"] == "YES":
                            #     final_output = output_rewriter["text"]

                            if user_question == "":
                                continue
                            
                            else:
                                # rewritten_question = output_rewriter["text"]
                                rewritten_question = "previous QA:" + previous_QA + "\ncurrent question:" + user_question
                                
                                print("________Select columns and values________")
                                input_data = {
                                    "evidence": "",
                                    "db_name": db_name,
                                    "db_desc": db_getdesc(db_name),
                                    "db_exam": get_example(db_name),
                                    "question": rewritten_question 
                                }
                                
                                output_selector = selector.process_input(input_data)
                                
                                print("________Question type detect________")
                                input_data = {
                                    "evidence": "",
                                    "db_name": db_name,
                                    "db_desc": db_getdesc(db_name),
                                    "mini_schema": output_selector,
                                    "question": rewritten_question
                                }
                                
                                output_detector = detector.process_input(input_data)
                                # print("output_detectoroutput_detectoroutput_detector" + output_detector)
                                # The question is Answerable
                                print(output_detector)
                                if output_detector == "YES":
                                    
                                    print("________Decompose question and solve________")
                                    input_data = {
                                    "evidence": "",
                                    "db_name": db_name,
                                    "mini_schema": output_selector,
                                    "question": rewritten_question
                                    }
        
                                    output_decomposer = decomposer.process_input(input_data)
                                    print(output_decomposer)
                                    
                                    if output_decomposer["executable"]:
                                        final_output = output_decomposer["sql"]
                                        # sql_output = " Result:" + str(output_decomposer["result"])
                                    else:
                                        
                                        print("________Refines erroneous SQL queries________")
                                        input_data = {
                                        "evidence": "",
                                        "db_name": db_name,
                                        "mini_schema": output_selector,
                                        "question": rewritten_question,
                                        "old_sql": output_decomposer.get("sql"),
                                        "log": output_decomposer.get("log")
                                        }
                                        
                                        
                                        output_refiner = refiner.process_input(input_data)
                                        # print(output_refiner)
                                        print(output_refiner)
                                        final_output = output_refiner["sql"]
                                        
                                        # if output_decomposer["executable"]:
                                        #     sql_output = " Result:" + str(output_refiner["result"])
                                    
                                else:
                                    final_output = output_detector
                                    
                            # llm record
                            print("\nFINAL Response:")
                            print(final_output)
                            print("————————————————————————————————————————————————————————————")
                            item['turns'][index+1]['predict'] = final_output
                            item['turns'][index+1]['Rewriter'] = output_rewriter
                            item['turns'][index+1]['Selector'] = output_selector
                            item['turns'][index+1]['Detector'] = output_detector
                            item['turns'][index+1]['Decomposer'] = output_decomposer
                            item['turns'][index+1]['Refiner'] = output_refiner
                            
                            # update messages
                            g_ans = ""
                            if item['turns'][index+1]['text']:
                                g_ans = item['turns'][index+1]['text']
                            else:
                                g_ans = item['turns'][index+1]['query']
                            if question_type == "answerable":
                                sql_result = sql_evoke(g_ans,db_name)
                                sql_output = " Result:" + str(sql_result)
                            # previous_QA += "\nQ:" + user_question + "\nA:" + g_ans + sql_output + '\n'
                            previous_QA += "\nQ:" + user_question + "\nA:" + g_ans + '\n'
                            
                            
                if not os.path.exists(output_file):
                    with open(output_file, 'w') as f:
                        items = [item]
                        json.dump(items, f, indent=4)
                        f.write('\n')
                else:
                    with open(output_file, 'r') as f:
                        try:
                            items = json.load(f)
                        except json.JSONDecodeError:
                            print("\033[91mError:The file content is not in valid JSON format\033[0m")
                            # items = []
        
                    if not isinstance(items, list):
                        print("\033[91mError:The file content is not in valid JSON format\033[0m")
                        # items = []
        
                    items.append(item)
        
                    with open(output_file, 'w') as f:
                        json.dump(items, f, indent=4)
                        f.write('\n')
                break
            except Exception as e:
                retries += 1
                print(f"Error processing turn {index} (attempt {retries}): {e}")

with  open('datasets/MMSQL_test.json', 'r', encoding='utf-8') as f:
        data = json.load(f)
    
process_json_part(data[51:100],'agenttest1012.json')

  0%|                                                                                                                                                                                                                                                                                   | 0/49 [00:00<?, ?it/s]

Turn 0 ==================================================================
previous_QA :
question 0: How many battles did not lose any ship with tonnage 225?

________Select columns and values________
request gemini-1.5-flash
('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
Success: Operation completed after 0 retries
{
  "battle": ["id", "name", "date", "bulgarian_commander", "latin_commander", "result"],
  "ship": ["lost_in_battle", "id", "name", "tonnage", "ship_type", "location", "disposition_of_ship"],
  "death": "drop_all"
}
________Question type detect________
request gemini-1.5-flash
('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
Success: Operation completed after 0 retries
YES
________Decompose question and solve________
request gemini-1.5-flash
Success: Operation completed after 0 retries
{'result': [(7,)], 'sql': "SELECT COUNT(DISTINCT T1.id) FROM battle AS T1 WHERE T1.id NOT IN ( SELECT DISTINCT T1.id FROM battle AS T1 INNER JOIN ship AS T2 ON T1.id = T2.lost_in_battle WHERE T2.tonnage = '225' )", 'executable': True, 'log': '', 'process': "Subquestion 1: Find the battles that lost ships with tonnage 225.\nSQL ```sql SELECT DISTINCT T1.id FROM battle AS T1 INNER JOIN ship AS T2 ON T1.id = T2.lost_in_battle WHERE T2.tonnage = '225'```\nSubquestion 2: Find the battles that did not lose any ship with tonnage 225.\nSQL ```sql SELECT COUNT(DISTINCT T1.id) FROM battle AS T1 WHERE T1.id NOT IN ( SELECT DISTINCT T1.id FROM battle AS T1 INNER JOIN ship AS T2 ON T1.id = T2.lost_in_battle WHERE T2.tonnage = '225' )```\n\nQuestion Solved. \n"}

FINAL Response:
SELECT COUNT(DISTINCT T1.id) FROM battle AS T1 WHERE T1.id NOT IN ( SELECT DISTINCT T1.id FROM battle AS T1 INNER JOIN ship AS T2 ON T1.id = T2.lost_in_battle WHERE T2.tonnage = '225' )
————————————————————————————————————————————————————————————
previous_QA :
Q:How many battles did not lose any ship with tonnage 225?

A:SELECT count(*) FROM battle WHERE id NOT IN ( SELECT lost_in_battle FROM ship WHERE tonnage  =  '225' );

question 1: How many battles did lose a ship with tonnage 225?
________Select columns and values________
request gemini-1.5-flash
Success: Operation completed after 0 retries
{
  "battle": ["id", "name", "date", "bulgarian_commander", "latin_commander", "result", "lost_in_battle"],
  "ship": ["id", "name", "tonnage", "ship_type", "location", "disposition_of_ship", "lost_in_battle"],
  "death": "drop_all"
}
________Question type detect________
request gemini-1.5-flash
Success: Operation completed after 0 retries
YES
________Decompose question and solve________
request gemini-1.5-flash
('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
Success: Operation completed after 0 retries
{'result': [(1,)], 'sql': "SELECT COUNT(DISTINCT lost_in_battle) FROM ship WHERE tonnage = '225'", 'executable': True, 'log': '', 'process': "Subquestion 1: Find the battles that lost a ship with tonnage 225.\nSQL ```sql SELECT DISTINCT lost_in_battle FROM ship WHERE tonnage = '225'```\nSubquestion 2: Count the number of battles that lost a ship with tonnage 225.\nSQL ```sql SELECT COUNT(DISTINCT lost_in_battle) FROM ship WHERE tonnage = '225'```\n\nQuestion Solved. \n"}

FINAL Response:
SELECT COUNT(DISTINCT lost_in_battle) FROM ship WHERE tonnage = '225'
————————————————————————————————————————————————————————————
previous_QA :
Q:How many battles did not lose any ship with tonnage 225?

A:SELECT count(*) FROM battle WHERE id NOT IN ( SELECT lost_in_battle FROM ship WHERE tonnage  =  '225' );

Q:How many battles did lose a ship with tonnage 225?
A:SELECT count(*) FROM battle WHERE id IN ( SELECT lost_in_battle FROM ship WHERE tonnage  =  '225' );

question 2: How many ships have a tonnage of 225?

________Select columns and values________
request gemini-1.5-flash
Success: Operation completed after 0 retries
{
  "battle": "drop_all",
  "ship": ["tonnage", "id", "lost_in_battle"],
  "death": "drop_all"
}
________Question type detect________
request gemini-1.5-flash
Success: Operation completed after 0 retries
YES
________Decompose question and solve________
request gemini-1.5-flash
('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
Success: Operation completed after 0 retries
{'result': [(1,)], 'sql': "SELECT COUNT(*) FROM ship WHERE tonnage = '225'", 'executable': True, 'log': '', 'process': "Subquestion 1: How many ships have a tonnage of 225?\nSQL ```sql SELECT COUNT(*) FROM ship WHERE tonnage = '225'```\n\nQuestion Solved. \n"}

FINAL Response:
SELECT COUNT(*) FROM ship WHERE tonnage = '225'
————————————————————————————————————————————————————————————
previous_QA :
Q:How many battles did not lose any ship with tonnage 225?

A:SELECT count(*) FROM battle WHERE id NOT IN ( SELECT lost_in_battle FROM ship WHERE tonnage  =  '225' );

Q:How many battles did lose a ship with tonnage 225?
A:SELECT count(*) FROM battle WHERE id IN ( SELECT lost_in_battle FROM ship WHERE tonnage  =  '225' );

Q:How many ships have a tonnage of 225?

A:SELECT count(*) FROM ship WHERE tonnage  =  '225'

question 3: Do any ships have a tonnage above 225?

________Select columns and values________
request gemini-1.5-flash
Success: Operation completed after 0 retries
{
  "battle": ["id", "name", "date", "bulgarian_commander", "latin_commander", "result"],
  "ship": ["id", "name", "tonnage", "ship_type", "location", "disposition_of_ship", "lost_in_battle"],
  "death": "drop_all"
}
________Question type detect________
request gemini-1.5-flash
Success: Operation completed after 0 retries
YES
________Decompose question and solve________
request gemini-1.5-flash
Success: Operation completed after 0 retries
{'result': [(6,)], 'sql': "SELECT COUNT(*) FROM ship WHERE tonnage > '225'", 'executable': True, 'log': '', 'process': "Subquestion 1: Find the ships with tonnage above 225.\nSQL ```sql SELECT COUNT(*) FROM ship WHERE tonnage > '225'```\n\nQuestion Solved. \n"}

FINAL Response:
SELECT COUNT(*) FROM ship WHERE tonnage > '225'
————————————————————————————————————————————————————————————
previous_QA :
Q:How many battles did not lose any ship with tonnage 225?

A:SELECT count(*) FROM battle WHERE id NOT IN ( SELECT lost_in_battle FROM ship WHERE tonnage  =  '225' );

Q:How many battles did lose a ship with tonnage 225?
A:SELECT count(*) FROM battle WHERE id IN ( SELECT lost_in_battle FROM ship WHERE tonnage  =  '225' );

Q:How many ships have a tonnage of 225?

A:SELECT count(*) FROM ship WHERE tonnage  =  '225'

Q:Do any ships have a tonnage above 225?

A:SELECT count(*) FROM ship WHERE tonnage  >  '225'

question 4: Who won in the battle when the ship with a tonnage of 225 was sunk?
________Select columns and values________
request gemini-1.5-flash
Success: Operation completed after 0 retries
{
  "battle": [
    "result",
    "id",
    "name",
    "date",
    "bulgarian_commander",
    "latin_commander",
    "lost_in_battle"
  ],
  "ship": [
    "tonnage",
    "id",
    "name",
    "ship_type",
    "location",
    "disposition_of_ship",
    "lost_in_battle"
  ],
  "death": "drop_all"
}
________Question type detect________
request gemini-1.5-flash
Success: Operation completed after 0 retries
YES
________Decompose question and solve________
request gemini-1.5-flash
Success: Operation completed after 0 retries
{'result': [], 'sql': "SELECT result FROM battle WHERE id = (SELECT lost_in_battle FROM ship WHERE tonnage = '225' AND disposition_of_ship = 'Wrecked')", 'executable': True, 'log': '', 'process': "Subquestion 1: Find the battle ID where the ship with tonnage 225 was sunk.\nSQL: ```sql SELECT lost_in_battle FROM ship WHERE tonnage = '225' AND disposition_of_ship = 'Wrecked'```\nSubquestion 2: Find the result of the battle with the ID found in the previous subquestion.\nSQL: ```sql SELECT result FROM battle WHERE id = (SELECT lost_in_battle FROM ship WHERE tonnage = '225' AND disposition_of_ship = 'Wrecked')```\n\nQuestion Solved. \n"}

FINAL Response:
SELECT result FROM battle WHERE id = (SELECT lost_in_battle FROM ship WHERE tonnage = '225' AND disposition_of_ship = 'Wrecked')
————————————————————————————————————————————————————————————
previous_QA :
Q:How many battles did not lose any ship with tonnage 225?

A:SELECT count(*) FROM battle WHERE id NOT IN ( SELECT lost_in_battle FROM ship WHERE tonnage  =  '225' );

Q:How many battles did lose a ship with tonnage 225?
A:SELECT count(*) FROM battle WHERE id IN ( SELECT lost_in_battle FROM ship WHERE tonnage  =  '225' );

Q:How many ships have a tonnage of 225?

A:SELECT count(*) FROM ship WHERE tonnage  =  '225'

Q:Do any ships have a tonnage above 225?

A:SELECT count(*) FROM ship WHERE tonnage  >  '225'

Q:Who won in the battle when the ship with a tonnage of 225 was sunk?
A:SELECT result FROM battle WHERE id IN ( SELECT lost_in_battle FROM ship WHERE tonnage  =  '225' );

question 5: Thanks!
________Select columns and values________
request gemini-1.5-flash
Success: Operation completed after 0 retries
{
  "battle": [
    "id",
    "name",
    "result",
    "latin_commander",
    "bulgarian_commander",
    "date"
  ],
  "ship": [
    "lost_in_battle",
    "id",
    "tonnage",
    "name",
    "ship_type",
    "location",
    "disposition_of_ship"
  ],
  "death": "keep_all"
}
________Question type detect________
request gemini-1.5-flash
Success: Operation completed after 0 retries
YES
________Decompose question and solve________
request gemini-1.5-flash

  2%|█████▍                                                                                                                                                                                                                                                                     | 1/49 [00:29<23:40, 29.59s/it]

Success: Operation completed after 0 retries
{'result': [(1,)], 'sql': "SELECT COUNT(DISTINCT lost_in_battle) FROM ship WHERE tonnage = '225'", 'executable': True, 'log': '', 'process': "Subquestion 1: Find the battles where a ship with tonnage 225 was lost.\nSQL: ```sql SELECT lost_in_battle FROM ship WHERE tonnage = '225'```\n\nSubquestion 2: Count the number of battles where a ship with tonnage 225 was lost.\nSQL: ```sql SELECT COUNT(DISTINCT lost_in_battle) FROM ship WHERE tonnage = '225'```\n\nQuestion Solved. \n"}

FINAL Response:
SELECT COUNT(DISTINCT lost_in_battle) FROM ship WHERE tonnage = '225'
————————————————————————————————————————————————————————————
Turn 1 ==================================================================
previous_QA :
question 0: tell me the FullName of the maker amc
________Select columns and values________
request gemini-1.5-flash
Success: Operation completed after 0 retries
{
  "continents": "drop_all",
  "countries": "keep_all",
  "car_makers": ["FullName", "Maker", "Id", "Country"],
  "model_list": "keep_all",
  "car_names": "keep_all",
  "cars_data": "drop_all"
}
________Question type detect________
request gemini-1.5-flash
Success: Operation completed after 0 retries
YES
________Decompose question and solve________
request gemini-1.5-flash
('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
Success: Operation completed after 0 retries
{'result': [('American Motor Company',)], 'sql': "SELECT FullName FROM car_makers WHERE Id = (SELECT Id FROM car_makers WHERE Maker = 'amc')", 'executable': True, 'log': '', 'process': 'Subquestion 1: Find the Id of the maker "amc".\nSQL ```sql SELECT Id FROM car_makers WHERE Maker = \'amc\'```\nSubquestion 2: Get the FullName of the maker with the Id found in the previous step.\nSQL ```sql SELECT FullName FROM car_makers WHERE Id = (SELECT Id FROM car_makers WHERE Maker = \'amc\')```\n\nQuestion Solved. \n'}

FINAL Response:
SELECT FullName FROM car_makers WHERE Id = (SELECT Id FROM car_makers WHERE Maker = 'amc')
————————————————————————————————————————————————————————————
previous_QA :
Q:tell me the FullName of the maker amc
A:SELECT Fullname FROM car_makers WHERE maker = "amc"

question 1: Tell me CountryName for Countryid  1, 2, and 3.
________Select columns and values________
request gemini-1.5-flash
Success: Operation completed after 0 retries
{
  "continents": "drop_all",
  "countries": ["CountryId", "CountryName", "Continent"],
  "car_makers": "drop_all",
  "model_list": "drop_all",
  "car_names": "drop_all",
  "cars_data": "drop_all"
}
________Question type detect________
request gemini-1.5-flash